### ISSUE TITLE
standings page

### ISSUE THREAD

**Issue by pbullion** [pbullion/TDMPFFL#1]
@kevincolten
any idea why the standings page would not be listing the info? i got the other pages working..

switched over to pygres and heroku instead of mysql and it took a few to learn that and switched the site over to that.

[standings page](https://github.com/pbullion/TDMPFFL/blob/master/templates/standings.html#L22-L30)
[app location](https://github.com/pbullion/TDMPFFL/blob/master/app.py#L47-L51)

**Comment by pbullion** [comment]
<img width="1440" alt="screen shot 2017-01-07 at 10 12 44 pm" src="https://cloud.githubusercontent.com/assets/20978249/21747251/788f5b68-d526-11e6-8b2c-5b5897b4e079.png">

**Comment by kevincolten** [comment]
Are you getting anything if you log [`result_list`](https://github.com/pbullion/TDMPFFL/blob/master/tdmpfflClass.py#L65) here ?

**Comment by pbullion** [comment]
fixed it....i had [year](https://github.com/pbullion/TDMPFFL/blob/master/tdmpfflClass.py#L67) in 'year'....dumb dumb

@kevincolten

**Comment by kevincolten** [comment]
nice

**Comment by pbullion** [comment]
@kevincolten yea in pycharm it was changing colors so i thought it was something i needed to escape in the query but apparently it did more harm than good.
